// Sound resource definitions...
#define gShotSound	0
#define gMultiplier	1
#define gExplosionSound	2
#define gShipHitSound	3
#define gBoom1		4
#define gBoom2		5
#define gMultiplierGone	6
#define gMultShotSound	7
#define gSteelHit	8
#define gBonk		9
#define gRiff		10
#define gPrizeAppears	11
#define gGotPrize	12
#define gGameOver	13
#define gNewLife	14
#define gBonusAppears	15
#define gBonusShot	16
#define gNoBonus	17
#define gGravAppears	18
#define gHomingAppears	19
#define gShieldOnSound	20
#define gNoShieldSound	21
#define gNovaAppears	22
#define gNovaBoom	23
#define gLuckySound	24
#define gDamagedAppears	25
#define gSavedShipSound	26
#define gFunk		27
#define gEnemyAppears	28
#define gPrettyGood	31
#define gThrusterSound	32
#define gEnemyFire	33
#define gFreezeSound	34
#define gIdiotSound	35
#define gPauseSound	36
